version: "3"

services:
  app:
    build: .
    command: npm start
    links:
      - postgres
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app

  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reguser
